# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='duixiang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to=b'')),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('m', '\u7537'), ('f', '\u5973')], max_length=10)),
                ('university', models.CharField(max_length=20)),
                ('grade', models.PositiveSmallIntegerField(choices=[(1, '\u5927\u4e00'), (2, '\u5927\u4e8c'), (3, '\u5927\u4e09'), (4, '\u5927\u56db')])),
                ('homeland', models.CharField(max_length=10)),
                ('major', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=20)),
                ('income', models.CharField(choices=[('poor', '\u8d2b\u7a77'), ('normal', '\u4e00\u822c'), ('rich', '\u5bcc\u88d5'), ('super', '\u571f\u8c6a')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('origin', models.FileField(upload_to=b'')),
                ('ctic', models.TextField(blank=True)),
            ],
        ),
    ]
