# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-23 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wxwz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateField()),
                ('pos', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('title_type', models.CharField(choices=[('zy', '\u76f4\u8a00'), ('as', '\u6697\u793a'), ('xz', '\u65b0\u77e5'), ('tw', '\u63d0\u95ee'), ('ml', '\u547d\u4ee4'), ('pd', '\u76d8\u70b9'), ('rx', '\u4eba\u6027'), ('dr', '\u4ee3\u5165'), ('jq', '\u8282\u6c14'), ('rd', '\u70ed\u70b9'), ('zht', '\u77e5\u4e4e\u4f53'), ('dbkz', '\u5bf9\u6bd4\u5938\u5f20')], max_length=10)),
                ('con_type', models.CharField(max_length=10)),
                ('share', models.IntegerField(blank=True)),
                ('view', models.IntegerField(blank=True)),
                ('like', models.IntegerField(blank=True)),
                ('forward', models.IntegerField(blank=True)),
                ('score', models.IntegerField(blank=True)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('author', models.CharField(blank=True, max_length=10)),
                ('center', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
